baseURL = "https://seandavi.github.io/genetics_branch_retreat_site/"
languageCode = "en-us"
title = "Genetics Branch Retreat 2020"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Genetics Branch, NCI"
    description = "Virtual abstract book for the Genetics Branch Retreat, November 6, 2020"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1



[[menu.main]]
    url = "/abstract/"
    name = "Abstracts"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "PI Index"
    weight = 4

